- name: Scala is downloaded
  get_url:
    url=http://www.scala-lang.org/files/archive/scala-2.11.5.deb
    dest=/tmp/scala-2.11.5.deb

- name: Scala is present
  apt:
    deb=/tmp/scala-2.11.5.deb
  tags: [scala]

- name: Download SBT
  get_url:
    url=https://dl.bintray.com/sbt/debian/sbt-0.13.7.deb
    dest=/tmp/sbt-0.13.7.deb

- name: SBT is present
  apt:
    deb=/tmp/sbt-0.13.7.deb